/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calc_CONSTANTS_H
#define calc_CONSTANTS_H

#include "calc_types.h"



class calcConstants {
 public:
  calcConstants();

};

extern const calcConstants g_calc_constants;



#endif
